# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: release

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Get tag name
        id: git-tag
        run: echo ::set-output name=git-version::$(echo ${GITHUB_REF/refs\/tags\//} | cut -d 2-)

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: v${{ steps.git-tag.outputs.git-version }}

      - name: Get npm version
        id: npm-tag
        uses: martinbeentjes/npm-get-version-action@master

      - name: Compare versions
        run: |
          echo git ${{ steps.git-tag.outputs.git-version }}
          echo npm ${{ steps.npm-tag.outputs.current-version}}

